### PR TITLE
Xing OAuth implementation

### PR DESCRIPTION
**Pull request by visiongeist**
Xing is a large business network website mainly for German speakers.
Of course they provide an Oauth (v1) implementation

Here are the docs: https://dev.xing.com/docs/authentication

Please merge :)

### CODE REVIEW

**Comment by nraboy** [comment]
Probably silly to ask, but can you confirm that you've tested that this works?

If yes I'll merge it.

Best,

**Comment by visiongeist** [comment]
Yep. It's tested, if you want I can pass you the client key and secret to test it yourself. though I confirmed just now that it works ;)

**Comment by nraboy** [comment]
Thank you for contributing!

**Comment by visiongeist** [comment]
cool. when you going to release it?

**Comment by nraboy** [comment]
I usually merge to master after a few commits.  Maybe a week or two.

**Pull request merged**
