### PR TITLE
Making pull request again development branch

### PR DESCRIPTION
**Pull request by amit777**
This prevents various OAuth providers from making global changes to the $http headers.

### CODE REVIEW

**Comment by nraboy** [comment]
Travis CI failed.  Can you please take a look at the reasons for failure and correct them?

Best,

cc @matheusrocha89

**Comment by matheusrocha89** [comment]
@amit777 it's failing on npm install try to run again to see if is just some instability.

**Comment by amit777** [comment]
hmm.. sorry, I'm a bit of a n00b with Travis CI.  The only way to rerun the CI is by submitting another PR or by someone with write access to the repo to refresh (according to this link at least: http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit)

I didn't update the package.json file so I'm not sure how my updates would cause a break there?

**Comment by nraboy** [comment]
Run `grunt test`.  Travis will run this every time you do a push.  Do this with your Terminal.

**Comment by matheusrocha89** [comment]
Yes, then you can see if it's a code problem or a travis ci network problem
to do npm install

Em dom, 10 de jul de 2016 00:50, Nic Raboy <notifications@github.com>
escreveu:

> Run grunt test. Travis will run this every time you do a push. Do this
> with your Terminal.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nraboy/ng-cordova-oauth/pull/267#issuecomment-231569187>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADi83v_-AcZ9OZUn1bmZb_-nSWM0btFpks5qUGwIgaJpZM4JFu-N>
> .
>
-- 
Matheus Cruz Rocha
Engenheiro de Software
+55 (71) 99198-3176

**Comment by amit777** [comment]
got it... looks like everything is green!

**Comment by nraboy** [comment]
Thanks for contributing!  You're now officially more knowledgeable about GitHub :-)

**Pull request merged**
