### PR TITLE
Added ADFS as OAuth service

### PR DESCRIPTION
**Pull request by kromkens**

### CODE REVIEW

**Comment by nraboy** [comment]
Just to confirm, you've tested this code with a functional ADFS service?

The reason I ask is, due to my zero knowledge of ADFS, I'm putting a lot of trust in you that this works because I cannot test it myself.

If it works, this looks great :)

**Comment by nraboy** [comment]
Also, is `relyingPartyId` able to be set to `http://localhost/callback` in the ADFS dashboard?  For consistency, I like to force all callbacks in this library to that URL unless it absolutely cannot be set to that.

Thanks,

**Comment by kromkens** [comment]
I tested the code against against a functional ADFS server. However, with regards to the `relyingPartyId`, I still have to test if that can be set to `http://localhost/callback`

That will have to wait till next week though, because I have no access to the ADFS server now.

**Comment by kromkens** [comment]
I checked with regards to the `relyingPartyId` and in production scenario's it can not be set to `http://localhost/callback` , because it is the resource that is relying on ADFS for authentication. So nearly always a resource in the same domain as the ADFS server.

Another thing to mention is that this solution works from ADFS 3.0 on "out of the box". Earlier versions of ADFS require additional setup for the AOuth end-point.

**Comment by nraboy** [comment]
Thanks for your thorough information.  Helps people like me who aren't familiar with it.  I'll make sure to include all this information in the README after I merge.

Thanks,

**Comment by kromkens** [comment]
When I've done some more testing on the `redirect_uri` and `relyingPartyId` and know everything works as expected, then I'll also provide you with proper documentation for the README.

**Pull request merged**
