### PR TITLE
Add support for Authorization Code Flow for Spotify API

### PR DESCRIPTION
**Pull request by PythagoRascal**

### CODE REVIEW

**Comment by nraboy** [comment]
Hey @PythagoRascal,

This "authorization code flow", can you give me some details on it?  Is this an explicit grant type or some other proprietary function of the Spotify API?

Thanks,

**Comment by PythagoRascal** [comment]
Hey @nraboy 

It's what Spotify calls it in their API docs [here](https://developer.spotify.com/web-api/authorization-guide/#authorization-code-flow). 

>**Authorization Code Flow**
>This method is suitable for long-running applications which the user logs into once. It provides an access token that can be refreshed. Since the token exchange involves sending your secret key, this should happen on a secure location, like a backend service, not from a client like a browser or mobile apps. This flow is described in RFC-6749. This flow is also the authorization flow used in our Web API Tutorial.

Basically, I call the /authorize endpoint in the frontend where I need the user to grant access to my app and then pass the authorization code to the backend. There I exchange the code with a call to the /authorize endpoint for an access token and a refresh token. Hope that clarifies it a bit.

Cheers

**Comment by neophob** [comment]
+1

**Comment by PythagoRascal** [comment]
@nraboy if there is something you'd like me to change/fix before you merge this in, please let me know. I'll get to it as fast as I can.

**Comment by matheusrocha89** [comment]
@PythagoRascal The code seems fine. Did you tested both ways of login with your changes? The old way without the authorization code and the new way with authorization code?

**Comment by PythagoRascal** [comment]
@matheusrocha89 yes, they both worked fine.

**Comment by nraboy** [comment]
Thanks @PythagoRascal!

The change will end up in our staging branch next week for testing.  If all is good we'll push it to the master shortly after.

Thanks for contributing :-)

**Comment by PythagoRascal** [comment]
Wonderful, thanks!

**Pull request merged**
