### PR TITLE
Added support for Instagram code auth

### PR DESCRIPTION
**Pull request by ballmw**
We use instagram codes to auth users from our server.  I've added a way to override access_token auth via the options.

Thanks!

### CODE REVIEW

**Comment by nraboy** [comment]
Please excuse my lack of knowledge on this, but do Instagram codes require a client secret key?  Please link me to any relevant documentation so we have it with the pull request.

Thanks,

**Comment by ballmw** [comment]
They do require a secret key.  We did not want to enable instagram's implicit auth for our clientid b/c it's the same one our web site uses.  Implicit auth is less secure especially for web sites:

https://instagram.com/developer/authentication/?hl=en

**Comment by nraboy** [comment]
I see what you're after now.  You wan't to send the authentication code to your server to then complete the flow.  I was skeptical, because I'd like to prevent people from having their secret key client side whenever possible.  This is not the case in your scenario.

I'm fine with this, but before I merge, I'd like to confirm that you've tested both the implicit and explicit grant in the library after making the change?

Thanks,

**Comment by ballmw** [comment]
I'll re-test today just to confirm and let you know.

**Comment by ballmw** [comment]
Ok, I've confirmed it works.  I can provide sample project if necessary.

**Comment by nraboy** [comment]
I trust you!  I'm glad you took the time to re-test it for me :-)

Thank you for contributing to the project.

**Pull request merged**
