### PR TITLE
Allow sending of options to window.open

### PR DESCRIPTION
**Pull request by yotamlaufer**
In many cases you will need to send extra settings to window.open to preserve app state. For example when your application plays video and is configured to play the video inline on iOS these setting will be nullified. To preserve the behavior we must send more options to ```window.open```. This fix enables this by adding another argument to ```$cordovaOauth.<provider>```

Example:

```
$cordovaOauth.facebook(clientKey, permissions, {}, 'allowInlineMediaPlayback=yes,mediaPlaybackRequiresUserAction=no').then(...)
```

### CODE REVIEW

**Comment by yotamlaufer** [comment]
@nraboy did you get a chance to review?

**Comment by yotamlaufer** [comment]
Please note that there was an issue with Facebook login that was inconsistent with code on the master branch. I have commited a fix.

**Comment by nraboy** [comment]
I'm assuming you did your own thorough testing on this, correct?

I merged it into the development branch.  When I have few more items merged in I will merge with the master.

Thanks for contributing :-)

**Comment by yotamlaufer** [comment]
I tested, but I also noticed that master and development are quite apart. A code review is necessary at this point in my opinion.

**Comment by nraboy** [comment]
The development branch should only be behind the master.  It should not be "different".  Have I missed something and accepted a bad PR?

Always open to feedback.

Thanks,

**Comment by yotamlaufer** [comment]
The most evident case that I could see was the Facebook login method, which seems to have landed in my fork. Which is really strange, as this was a clean repo on my machine.

Seems that it’s all in order now.

What I would suggest though is splitting up the oauth section into smaller files. It will make maintenance much easier.

**Comment by nraboy** [comment]
Please see this from @matheusrocha89.  He is an awesome contributor and was working on that very thing:

https://github.com/nraboy/ng-cordova-oauth/pull/152

Since this is a hobby project of mine only, I rely heavily on the community to help me out as I often cannot dedicate too much time to feature improvements.

I'm incredibly grateful for you guys helping out!

Best,

**Comment by yotamlaufer** [comment]
@nraboy, thank you man, it’s great to have such a central repo for all of these auth methods. I’ll follow on that pull request and see if I can help with anything.

**Comment by matheusrocha89** [comment]
@yotamlaufer I am already doing this, but it have some conflicts with your PR could your answer me something, on the providers your changes was just adding a new params and changing the window.open to use your new function? Just that? Or you did some changes on other providers?

**Pull request merged**
