### PR TITLE
Added Jawbone authentication

### PR DESCRIPTION
**Pull request by aBuder**
Added support for Jawbone authentication
https://jawbone.com/up/developer/authentication

### CODE REVIEW

**Comment by nraboy** [comment]
Looks good, but before I merge, can I confirm that you tested that it works?

Thanks,

**Comment by aBuder** [comment]
Hi, Yes I test it :) and I use it

**Comment by aBuder** [comment]
Can You merge it do master ? I need it in my mobile app

**Comment by nraboy** [comment]
Sorry I was on vacation.

I don't merge development into master immediately.  I wait until I have multiple changes to include.  Your change is included in the development branch.  There is nothing wrong with using the development branch in your project for now since it is stable.

Regards,

**Pull request merged**
