### PR TITLE
Changed redirect_uri check to http://localhost/callback.

### PR DESCRIPTION
**Pull request by kromkens**
I changed the code so the `redirect_uri` is always `http://localhost/callback`. This `redirect_uri` must be configured as `redirect_uri` on the Client when registering the Client in ADFS. 

The `relyingPartyId` can not be standardized as this is the resource that is relying on ADFS for authentication. I.e. the resource you’re requesting an `access_token` for.

Let me know if you need more info.

### CODE REVIEW

**Comment by nraboy** [comment]
Hi @kromkens,

Can you fetch from the upstream and merge your changes?  It looks like your commit didn't sync up correctly.

Thanks,

**Comment by kromkens** [comment]
I fetched the upstream and merged. Could you try again?

**Comment by nraboy** [comment]
Thanks for your contribution :)

**Comment by kromkens** [comment]
Thanks you for the library in the first place!

**Pull request merged**
