### PR TITLE
add support for a compact header

### PR DESCRIPTION
**Pull request by seiyria**
ref: #77

### CODE REVIEW

**Comment by nraboy** [comment]
Seems like this should work, but can I confirm with you that you've tested it?

Thanks,

**Comment by seiyria** [comment]
It should work (quite a simple change) but I won't be able to test it for a while. I can confirm if it works at that time though.

**Comment by nraboy** [comment]
I merged it anyways.  When I have time I'll test it as well.  Since it is in the development branch, it is safe.

Thanks for contributing :-)

**Comment by seiyria** [comment]
Hey, no problem. I'm gonna need this feature pretty soon so I wanted to get it in before that comes. Thanks for creating this great set of OAuth mechanisms -- it takes a lot of the work off of me (especially because I'm new and it can be confusing!).

**Comment by DrBeza** [comment]
Hi there, I was looking over the master & development branch, it seems this PR/merge has gone with some refactoring in June.

**Comment by seiyria** [comment]
Yes, checking the development branch, I see [this](https://github.com/nraboy/ng-cordova-oauth/blob/development/src/oauth.js#L479-L490) -- the `compact` param is not used anywhere. Any idea what's up @nraboy?

**Comment by nraboy** [comment]
Did I accidentally wipe it out in the refactor?

**Comment by seiyria** [comment]
It seems so!

**Comment by DrBeza** [comment]
Added a PR https://github.com/nraboy/ng-cordova-oauth/pull/102

**Comment by nraboy** [comment]
Thanks

**Pull request merged**
