### PR TITLE
Added vk.com authentication

### PR DESCRIPTION
**Pull request by michaeleparkour**
$cordovaOauth.vkontakte("appId", ["scope"]).then(function(result) {
            // results
        }, function(error) {
            // error
        });

### CODE REVIEW

**Comment by nraboy** [comment]
Why did you choose `https://oauth.vk.com/blank.html` as the callback instead of `http://localhost/callback`?

**Comment by michaeleparkour** [comment]
It taken from documentation https://vk.com/dev/auth_mobile. The point is you can't set the redirect_uri for Desktop/Standalone applications, so there will be an error while authentificate

**Comment by nraboy** [comment]
Thanks for the explanation!

**Comment by michaeleparkour** [comment]
you're welcome!

**Pull request merged**
