### PR TITLE
Add googleOffline process

### PR DESCRIPTION
**Pull request by rschiano**
I added a googleOffline fonction to use the full process and allow google to give a refresh_code. 
In some applications you may need to use on a webserver (offline) a token created by the application.

### CODE REVIEW

**Comment by matheusrocha89** [comment]
@rschiano We are not receiving PR direct to master branch anymore, just on development. So, could you create a new one for development branch?

**Comment by nraboy** [comment]
This is not a good approach for two reasons:

1. It is using explicit grants.  We already have a Google connection with implicit, the safer approach for client side.  I only add explicit grant connections to services that do not offer implicit.
2. Even if we were to add the explicit grant as well, it should not be its own connection.  It should be integrated into the existing $cordovaOauth.google and chosen with a parameter vs implicit.

**Comment by rschiano** [comment]
@nraboy 
1/ It's needed in my case, i have to get a token from an application and save it on a server to make some offline job. It's less secure, but some people may be in the same case
2/ Totally approved, i started with and integrated version, but didn't had time to complete. I did a quick fix for my usage, i propose you a working version so you can properly implement it, but i will not have time to improve it.

I was just in a share working approach, if it's not in your way of think, just ignore it ;).

Just tell me if i should create a new one on development, or if it would be ignored.

**Comment by napcat** [comment]
I was trying to use this, but it's failing on the second call: "https://accounts.google.com/o/oauth2/token".

I get an error "400 - Bad request" and the promise is rejected with the message "Problem authenticating" .

The token I'm getting has only one hour.
After that, it gets expired and the user needs to enter his credentials again.

How can I refresh the token so the user doesn't need always enter his account details?

**Comment by nraboy** [comment]
Google support was removed as of https://github.com/nraboy/ng-cordova-oauth/commit/555b5caafbe0b7a552c6dc418e3353f6615f24da

Best,

**Pull request closed without merging**
