### PR TITLE
Improving code

### PR DESCRIPTION
**Pull request by matheusrocha89**
It seems that the new version of cordova it's breaking a few things when we call the `cordova.require("cordova/plugin_list").metadata`, the metadata it's returning an empty object even with plugins installed so I changed the code to find the inAppBrowser plugin without the metadata.

The other change I made was with the `window.open` method that we are using, reading the inAppBrowser docs I found this:
```
For backwards compatibility, this plugin also hooks window.open. 
However, the plugin-installed hook of window.open can have unintended 
side effects (especially if this plugin is included only as a dependency of 
another plugin). The hook of window.open will be removed in a future major release.
```
So knowing that they will remove this backwards compatibility I change all our calls of `window.open` to `cordova.InAppBrowser.open` just to avoid future problems with inAppBrowser plugin updates.

I want the opinion of you guys @nraboy, @youtabmedia

### CODE REVIEW

**Comment by nraboy** [comment]
I feel like we need to leave `cordova.require("cordova/plugin_list").metadata` in to preserve backwards compatibility.  I think it only breaks in the latest versions right?  Can we add something to preserve legacy functions for the people who aren't bleeding edge?

**Comment by matheusrocha89** [comment]
Sure, we can put an if statement just to maintain backward compatibility, I will do that now. :+1:

**Comment by nraboy** [comment]
I know you've been making a lot of changes.  Let me know when you think we have a stable release that I can push towards a staging branch for testing.

Looks like the changes in the latest Cordova with metadata is going to hit us hard

**Comment by matheusrocha89** [comment]
This version it seems stable. No, don't worry about the metadata :) I made a change that we don't even need it anymore but I let it there just for precaution and backward compatibility if some trouble appears hahahahaha. I tested with Instagram and everything was smooth. Try to test this version @nraboy

**Comment by nraboy** [comment]
Is this expected? It seems to have hung after running `grunt`:

screen shot 2015-11-15 at 9 08 35 am

**Comment by nraboy** [comment]
I'm also receiving this error when trying to use the minified dist file:

```
E/AndroidProtocolHandler( 2152): Unable to open asset URL: file:///android_asset/www/cordova_plugins.js
I/chromium( 2152): [INFO:CONSOLE(17696)] "Error: [$injector:unpr] Unknown provider: aProvider <- a <- $cordovaOauthUtility <- $cordovaOauth
I/chromium( 2152): http://errors.angularjs.org/1.2.25/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-%20%24cordovaOauthUtility%20%3C-%20%24cordovaOauth
I/chromium( 2152):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:7703:12
I/chromium( 2152):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11427:19
I/chromium( 2152):     at Object.getService [as get] (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11555:39)
I/chromium( 2152):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11432:45
I/chromium( 2152):     at getService (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11555:39)
I/chromium( 2152):     at Object.invoke (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11582:13)
I/chromium( 2152):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11433:37
I/chromium( 2152):     at getService (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11555:39)
I/chromium( 2152):     at Object.invoke (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11582:13)
I/chromium( 2152):     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:11433:37", source: file:///android_asset/www/lib/ionic/js/ionic.bundle.js (17696)
```

Did the commands change between the release and development version?

**Comment by matheusrocha89** [comment]
It is expectes, the grunt it's because of the autoWatch for tests, you can
give a ctrl+c after tests run than will work fine. Or just turn the
auoWatch false on karma.conf.js. The error with cordova plugins is some
instability with cordova, happened with me too, I just removed and add the
platforms again and everything was fine.
Em 15/11/2015 14:21, "Nic Raboy" <notifications@github.com> escreveu:

**Comment by matheusrocha89** [comment]
@nraboy I will open a new PR removing this autoWatch to run on default grunt task.

**Comment by matheusrocha89** [comment]
@nraboy which version of node are you using?

**Comment by nraboy** [comment]
I'm using Node 0.12.7.  A part of me says that Android error I am getting is nothing related to platforms.  Kind of looks like it didn't build the minified version correctly.

Will see about doing more testing this week.  Let's put a freeze on features and enhancements and work to get a stable release out.  Once we have something good for staging I will put out an open request for testers on Twitter.

**Comment by matheusrocha89** [comment]
Ok, could you pass me your minified version to test, cause on my minified version it's working, at least with the instagram oauth.

**Comment by nraboy** [comment]
I tested Facebook and nothing else.  Run `grunt build` and see if it works for you in regards to Facebook.

**Comment by matheusrocha89** [comment]
Ok, I will test it.

**Comment by matheusrocha89** [comment]
@nraboy works fine here with facebook.

image

**Comment by matheusrocha89** [comment]
@nraboy GREAT NEWS! Found the problem. Opening pull request now. After that I believe we will have a stable version to staging

**Pull request merged**
