### PR TITLE
Improving code of `inAppBrowser` verification

### PR DESCRIPTION
**Pull request by matheusrocha89**
This PR improves the verification of inAppBrowser plugin is installed creating a method to verify that and creating an array inside this function to make it easy to maintain the code if the name change it someday again.

### CODE REVIEW

**Comment by matheusrocha89** [comment]
@nraboy now on the right branch :+1:

**Comment by nraboy** [comment]
You're going to hate me for putting you through all this trouble, but can you fetch all the commits from the development branch and do a merge?  There is a conflict.

If I had more time, I would do it.

Thanks,

**Comment by matheusrocha89** [comment]
Sure, I can do that.

**Comment by matheusrocha89** [comment]
@nraboy already fixed the conflicts :+1:

**Comment by matheusrocha89** [comment]
Strange, still says that there are conflicts, let me look again

**Comment by matheusrocha89** [comment]
@nraboy Now, it's correct. :+1: was my bad, sorry :smile:

**Comment by nraboy** [comment]
Awesome!

Thank you so much for contributing :-)

**Pull request merged**
