### PR TITLE
Adding missing $inject on cordovaOauthUtility

### PR DESCRIPTION
**Pull request by matheusrocha89**
This missing $inject was generating a broken minified version.

Tested with facebook, Instagram and github.

Now I think we will have an stable version to staging.

### CODE REVIEW

**Comment by nraboy** [comment]
Think this fixes the problem I was getting?

I'm hoping to test a little bit today.

**Comment by matheusrocha89** [comment]
For sure it will i could simulate the error and that was the problem. Let's
make a staging version with this. And see if the testers approve, if they
approve we can launch this version because it will fix the problem with the
inappbrowser some of the users are having now.
Em 17/11/2015 10:40, "Nic Raboy" <notifications@github.com> escreveu:

**Comment by nraboy** [comment]
Not sure if this is related, but Twitter no longer works:

```
I/chromium( 2064): [INFO:CONSOLE(28)] """", source: file:///android_asset/www/js/app.js (28)
```

If that is an error, it is not very helpful.  I tested with Imgur and Facebook and both work fine.  My assumption is that Oauth 1.0 and Oauth explicit grants may be broken somewhere.

**Comment by matheusrocha89** [comment]
@nraboy I will take a look on that. Could be something when I was splitting the files, something missing, I will take a look. I will find the problem and fix. I will be very happy when we have an stable version. :+1: 

Just one thing can you give a context what it is in line 28 of app.js ??? Could be the app.js file, this test you are making it's open source?

**Comment by nraboy** [comment]
I was using this project to test:

https://github.com/nraboy/ng-cordova-oauth-example

I swapped out the current library files with the new ones from the development branch.

**Comment by matheusrocha89** [comment]
Ok, Nice... I will clone later and try to figure out what is the problem
with twitter.

2015-11-19 13:00 GMT-03:00 Nic Raboy <notifications@github.com>:

> I was using this project to test:
>
> https://github.com/nraboy/ng-cordova-oauth-example
>
> I swapped out the current library files with the new ones from the
> development branch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nraboy/ng-cordova-oauth/pull/163#issuecomment-158100459>
> .
>



-- 
Atenciosamente
--------------------------------------------------------
Matheus Cruz Rocha

 - *Desenvolvedor WEB e Mobile*

*(71) 9198-3176*

**Comment by matheusrocha89** [comment]
I am having some problems to test, the project always say that `cordova/plugins not found` are you having this problem? I google it but didn't found anything relevant about it

**Comment by nraboy** [comment]
Did you add the appropriate platform and plugins when you cloned the repo?

**Comment by matheusrocha89** [comment]
Sorry, my bad, forgot to add the plugin. 404 on twitter, I will test with the older version of ng-cordova-oauth

**Comment by matheusrocha89** [comment]
@nraboy Same problem with the old version, I think the url doesn't exist anymore or is down. Still in docs so I think it's down.

**Comment by matheusrocha89** [comment]
I think yesterday was some problems with twitter api. Now I am receiving 401 in both, new and old versions of `ng-cordova-oauth`

image

**Comment by nraboy** [comment]
I used the master branch of ng-cordova-oauth and added the ng-cordova-oauth.min.js into the example project.  I added the Android platform and all necessary plugins.

Twitter worked fine when I tested without a 401 error.  I received my access token fine.

Are you sure you created a Twitter application correctly via their dashboard?

**Comment by matheusrocha89** [comment]
@nraboy I tested the older and the new version of the ng-cordova-oauth and the login was fine. Without problems.

**Comment by matheusrocha89** [comment]
Are you still having problems with twitter @nraboy ?

**Comment by nraboy** [comment]
Haven't had a chance yet.  My free time is limited to only a few days per month.  I will give it a shot tonight.

**Comment by nraboy** [comment]
Weird, it works now.  Must have been an issue with Twitter.

Let me create a staging branch for testing.

**Comment by nraboy** [comment]
I created a staging branch.  Please share it with everyone you know and have them report testing results here:

https://github.com/nraboy/ng-cordova-oauth/issues/167

Thanks Matheus!

**Pull request merged**
