### PR TITLE
Include Google profile information

### PR DESCRIPTION
**Pull request by jdnichollsc**
It is necessary to get user data such as **displayName** and **photoURL** from Google

### CODE REVIEW

**Comment by nraboy** [comment]
A few things:

1. Can you link to the documentation that mentions this tag?  Would like to keep it as part of the project history.
2. Does this require a particular scope?  I don't mean require to be used, but I mean require to use oauth at all when it is included.
3. I don't accept pull requests on the `master` branch.  It is typically behind the `development` branch.  Instead you would need to clone the repository, checkout the `development` branch, apply your changes, then create a PR.

https://github.com/nraboy/ng-cordova-oauth#contribution-rules

I appreciate the contributions though :-)

**Comment by jdnichollsc** [comment]
I can't find this tag in the documentation, only debugging the firebase authentication like the following post https://groups.google.com/forum/#!topic/firebase-talk/35lFiZzzUII and testing with my Android device with **GapDebug**

**Comment by nraboy** [comment]
And you're sure it does not force extra permissions?

Make add your changes to the development branch and make a new PR and I'll merge it.

Best,

**Comment by matheusrocha89** [comment]
I think this could be an option to not force all users of the lib to include that on their authentication request, what do you think @nraboy and @jdnichollsc ?

**Comment by jdnichollsc** [comment]
@nraboy @matheusrocha89 Sorry for the delay, check the pull request https://github.com/nraboy/ng-cordova-oauth/pull/304

Best regards, Nicholls

**Comment by nraboy** [comment]
I am open to either as long as it doesn't force extra permissions.  Would you like it to default or would you like it to be an option?

cc @matheusrocha89 @jdnichollsc

**Comment by jdnichollsc** [comment]
Default option is good for me 👍

**Pull request closed without merging**
