### PR TITLE
Added missing '=' to scope parameter

### PR DESCRIPTION
**Pull request by tannerlinsley**

### CODE REVIEW

**Comment by matheusrocha89** [comment]
@nraboy I you can merge this one

**Comment by nraboy** [comment]
I will only merge to the development branch.  @tannerlinsley please do a `git checkout development` and make your changes there.

Regards,

**Comment by andrewoodleyjr** [comment]
+1

**Comment by matheusrocha89** [comment]
@Sorry @nraboy , didn't see it was in master branch

**Comment by tannerlinsley** [comment]
Sorry guys. I'll get this fixed up when I'm back to my computer.

**Pull request closed without merging**
